name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Trivy
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
          chmod +x trivy

      # Run Trivy scan for the Docker image
      - name: Scan Docker image
        run: |
          docker build -t my-app-image .
          ./trivy image --exit-code 1 --severity HIGH,CRITICAL my-app-image

      # Run Trivy scan for repository files
      - name: Scan repository for vulnerabilities
        run: |
          ./trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      # Save the Trivy report
      - name: Save Trivy report
        run: |
          ./trivy image --format table my-app-image > trivy-report.txt
          ./trivy fs --format table . >> trivy-report.txt

      # Upload Trivy report as an artifact
      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.txt
